export const assets = {
  logo: '/assets/logo.png',
  hero_img: '/assets/hero_img.png',
  cart_icon: '/assets/cart_icon.png',
  dropdown_icon: '/assets/dropdown_icon.png',
  exchange_icon: '/assets/exchange_icon.png',
  profile_icon: '/assets/profile_icon.png',
  quality_icon: '/assets/quality_icon.png',
  search_icon: '/assets/search_icon.png',
  star_dull_icon: '/assets/star_dull_icon.png',
  star_icon: '/assets/star_icon.png',
  bin_icon: '/assets/bin_icon.png',
  support_img: '/assets/support_img.png',
  menu_icon: '/assets/menu_icon.png',
  about_img: '/assets/about_img.png',
  contact_img: '/assets/contact_img.png',
  razorpay_logo: '/assets/razorpay_logo.png',
  stripe_logo: '/assets/stripe_logo.png',
  cross_icon: '/assets/cross_icon.png',
};